### ISSUE TITLE
Max concurrent needs to apply before resource costs.

### ISSUE THREAD

**Issue by danjacques** [maruel/pre-commit-go#13]
Currently, the concurrency restriction (`-C`) is applied [prior to executing a command](https://github.com/maruel/pre-commit-go/blob/daade278e7af266790d1f490a5f3bcda895b5f48/checks/config.go#L129). This effectively restricts the number of concurrent processes, but fails to restrict the number of spawned goroutines, which are spawned prior to `Capture` and merely blocked on output.

The original construction of concurrency restriction was written to lease the token prior to spawning any additional resources, including goroutines. This was accomplished by leasing the token in the iteration functions in [checks.go](https://github.com/maruel/pre-commit-go/blob/master/checks/checks.go) and [coverage.go](https://github.com/maruel/pre-commit-go/blob/master/checks/coverage.go). The approach was dropped in favor of simply limiting at `Capture`, but I think we should re-evaluate it.

Recent [luci-go](https://travis-ci.org/luci/luci-go/builds/120309374) runs are hitting thread resource limits:

```
17:57:12.725077 [go test -timeout 600s -v -race ./server/logdog/storage/bigtable] was slow: 3m0.78s
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f8cb2c20cc9 m=2
```

They also have massive stack traces of resources wasted waiting for goroutines, even with maximum concurrent processes set to 1. WDYT?

**Comment by danjacques** [comment]
Actually looking into it, tokens don't seem to be actually leased. This used to work, let me see what is not working...

**Comment by maruel** [comment]
Closing old issues, as recent Go versions made pcg less relevant.
