### ISSUE TITLE
pcg shouldn't install git hooks unless explicitly asked too

### ISSUE THREAD

**Issue by mithro** [maruel/pre-commit-go#17]
pcg currently does an "installrun" when run without any arguments which installs git hooks in your local repository. This means it is _really_ easy to accidentally install the hooks when you didn't mean / want too.

The reason this is bad is because the pcg hooks break many normal patterns of working with git (especially the pre-commit hook). If you have any untracked files then you can't commit at all (it just dies with complaints about untracked files). It also complains if you are trying to doing things like committing before running `gofmt` or `goimports`. The whole "commit frequently, commit often" approach is totally broken.

At the moment I find myself continually doing a `rm .git/hooks/pre-commit*`

An alternative other option would make it so that pcg hooks **never** blocks committing and instead just complain.

**Comment by maruel** [comment]
or only install it by default on push but not on commit, and only install on commit when requested manually?

**Comment by mithro** [comment]
That might be an okay compromise.

**Comment by maruel** [comment]
Closing old issues, as recent Go versions made pcg less relevant.
