### ISSUE TITLE
Support gopath mode for tests

### ISSUE THREAD

**Issue by alaska** [maruel/pre-commit-go#19]
Currently the test check seems to `go test ./...` from the root of the project, however some shops check in their entire gopaths, and it would be nice to only check the subset of tests involved with changed files.

**Comment by alaska** [comment]
This doesn't appear to be the actual problem.  It seems that in the environment I'm in, many many packages are listed as being changed that weren't touched.  I'll have to dig into this further.

**Comment by maruel** [comment]
Ok, ping me if you think there could be more debugging information. Something interesting would be to have a standalone tool that would print out the transiently affected packages, which would then be passed to 'go test' and other tools as-is.
