### ISSUE TITLE
pcg on chromium/luci tryservers

### ISSUE THREAD

**Issue by shishkander** [maruel/pre-commit-go#2]
The way current tryservers work is applying the patch on top the checked out ref. There is no "upstream" set. But that's exactly what [pcg needs](https://github.com/maruel/pre-commit-go/blob/4f990852821a33a5a1856ac4db4023bbb8f369d7/scm/repo.go#L202) and so it fails with "no upstream".

What's the best way forward? 
New mode for pcg which just considers last commit? Not use it on tryservers at all? Patch tryservers' logic?

**Comment by maruel** [comment]
Add flag -l for "last commit"
- or probably better -
"-a HEAD~1" as in "against <refish>"

**Comment by shishkander** [comment]
-a is already used to mean allFiles, which is actually related as -a implies "against gitNilCommit" . I can overload "-a" meaning in backwards compatible way, but it'll be confusing code.
Any ideas for good naming of new flag name?
