### ISSUE TITLE
Support for test (and other check?) sharding.

### ISSUE THREAD

**Issue by danjacques** [maruel/pre-commit-go#20]
The [luci-go](https://github.com/luci/luci-go) repository has been timing out its Travis build for a while now, doing too much for a single build round. One way to mitigate this would be to use Travis' [parallelization](https://docs.travis-ci.com/user/speeding-up-the-build/#Parallelizing-your-builds-across-virtual-machines) functionality to shard the single PCG execution into multiple smaller executions.

Notably, two things that consume a lot of time are:
* Unit tests (with `-race` enabled)
* Coverage generation

Idea would be to target these, break a given PCG run into `N` runs, provide `pcg` with its shard index, and then deterministically split (hopefully with some scattering) which tests and/or coverage a given shard does.

Proposed: for a given file, hash its path, take hash modulo `N`.

**Comment by maruel** [comment]
Ok but would it be faster to stop using travis and self-host?

**Comment by maruel** [comment]
Closing old issues, as recent Go versions made pcg less relevant.
