### ISSUE TITLE
pcg error, what is "cc"？

### ISSUE THREAD

**Issue by h1048576** [maruel/pre-commit-go#25]
os: windows
go: go version go1.10.1 windows/amd64

$ pcg
go test -timeout 15s -v -race ./internal/service/input failed:
# runtime/cgo
exec: "cc": executable file not found in %PATH%
FAIL     [build failed]

pcg: checks failed in 4.12s

**Comment by maruel** [comment]
Looks like it's trying to use cgo, are you testing something importing `"C"`?

**Comment by h1048576** [comment]
when i use go 1.9 (go version go1.9.1 windows/amd64), it works normal

when i use go 1.10 (go version go1.10.1 windows/amd64)
if i do this: go test -timeout 15s -v -race ./internal/service/input
the result is: exec: "cc": executable file not found in %PATH%
but when i remove the arg "-race" like this: go test -timeout 15s -v ./internal/service/input, it works normal

**Comment by maruel** [comment]
The -race detector requires gcc to be installed in recent Go versions on Windows.
